export default {
    MARK_NOTIFICATION_AS_READ_BY_ID:'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATIONS_AS_READ:'MARK_ALL_NOTIFICATIONS_AS_READ',
    MARK_START_NOTIFICATIONS_AS_READ:'MARK_START_NOTIFICATIONS_AS_READ',
    MARK_FINISH_NOTIFICATIONS_AS_READ:'MARK_FINISH_NOTIFICATIONS_AS_READ',
    RECEIVED_NOTIFICATIONS:'RECEIVED_NOTIFICATIONS',
    START_LOGIN:'START_LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    CHANGE_AVATAR:'CHANGE_AVATAR'
}